repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint src tests database main.py --rcfile=.pylintrc --fail-on=E,unused-import --fail-under=9.7
        language: unsupported
        types: [ python ]
        require_serial: true
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: unsupported
        types: [ python ]
        stages: [ pre-push ]
        always_run: true
        require_serial: true