crypto_dot_com_exchange_rest_endpoint: https://api.crypto.com/exchange/v1/
crypto_dot_com_exchange_websocket_endpoint: wss://stream.crypto.com/exchange/v1/
coin_market_cap_rest_endpoint: https://pro-api.coinmarketcap.com/
database_connection_host: localhost:5432